/*
 * generated by Xtext 2.12.0
 */
package uk.ac.kcl.inf.modelling.xdsml.ide


/**
 * Use this class to register ide components.
 */
class HenshinXDsmlSpecificationIdeModule extends AbstractHenshinXDsmlSpecificationIdeModule {
}
