/*
 * generated by Xtext 2.12.0
 */
package uk.ac.kcl.inf.modelling.xdsml.ide

import com.google.inject.Guice
import org.eclipse.xtext.util.Modules2
import uk.ac.kcl.inf.modelling.xdsml.HenshinXDsmlSpecificationRuntimeModule
import uk.ac.kcl.inf.modelling.xdsml.HenshinXDsmlSpecificationStandaloneSetup

/**
 * Initialization support for running Xtext languages as language servers.
 */
class HenshinXDsmlSpecificationIdeSetup extends HenshinXDsmlSpecificationStandaloneSetup {

	override createInjector() {
		Guice.createInjector(Modules2.mixin(new HenshinXDsmlSpecificationRuntimeModule, new HenshinXDsmlSpecificationIdeModule))
	}
	
}
