/**
 * generated by Xtext 2.12.0
 */
package uk.ac.kcl.inf.modelling.xdsml.henshinXDsmlSpecification;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

import org.eclipse.emf.henshin.model.Rule;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Henshin XDsml Specification</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link uk.ac.kcl.inf.modelling.xdsml.henshinXDsmlSpecification.HenshinXDsmlSpecification#getRules <em>Rules</em>}</li>
 * </ul>
 *
 * @see uk.ac.kcl.inf.modelling.xdsml.henshinXDsmlSpecification.HenshinXDsmlSpecificationPackage#getHenshinXDsmlSpecification()
 * @model
 * @generated
 */
public interface HenshinXDsmlSpecification extends EObject
{
  /**
   * Returns the value of the '<em><b>Rules</b></em>' reference list.
   * The list contents are of type {@link org.eclipse.emf.henshin.model.Rule}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Rules</em>' reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Rules</em>' reference list.
   * @see uk.ac.kcl.inf.modelling.xdsml.henshinXDsmlSpecification.HenshinXDsmlSpecificationPackage#getHenshinXDsmlSpecification_Rules()
   * @model
   * @generated
   */
  EList<Rule> getRules();

} // HenshinXDsmlSpecification
