/**
 * generated by Xtext 2.12.0
 */
package uk.ac.kcl.inf.modelling.xdsml.henshinXDsmlSpecification;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see uk.ac.kcl.inf.modelling.xdsml.henshinXDsmlSpecification.HenshinXDsmlSpecificationFactory
 * @model kind="package"
 * @generated
 */
public interface HenshinXDsmlSpecificationPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "henshinXDsmlSpecification";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.ac.uk/kcl/inf/modelling/xdsml/HenshinXDsmlSpecification";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "henshinXDsmlSpecification";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  HenshinXDsmlSpecificationPackage eINSTANCE = uk.ac.kcl.inf.modelling.xdsml.henshinXDsmlSpecification.impl.HenshinXDsmlSpecificationPackageImpl.init();

  /**
   * The meta object id for the '{@link uk.ac.kcl.inf.modelling.xdsml.henshinXDsmlSpecification.impl.HenshinXDsmlSpecificationImpl <em>Henshin XDsml Specification</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see uk.ac.kcl.inf.modelling.xdsml.henshinXDsmlSpecification.impl.HenshinXDsmlSpecificationImpl
   * @see uk.ac.kcl.inf.modelling.xdsml.henshinXDsmlSpecification.impl.HenshinXDsmlSpecificationPackageImpl#getHenshinXDsmlSpecification()
   * @generated
   */
  int HENSHIN_XDSML_SPECIFICATION = 0;

  /**
   * The feature id for the '<em><b>Metamodel</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int HENSHIN_XDSML_SPECIFICATION__METAMODEL = 0;

  /**
   * The feature id for the '<em><b>Units</b></em>' reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int HENSHIN_XDSML_SPECIFICATION__UNITS = 1;

  /**
   * The number of structural features of the '<em>Henshin XDsml Specification</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int HENSHIN_XDSML_SPECIFICATION_FEATURE_COUNT = 2;


  /**
   * Returns the meta object for class '{@link uk.ac.kcl.inf.modelling.xdsml.henshinXDsmlSpecification.HenshinXDsmlSpecification <em>Henshin XDsml Specification</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Henshin XDsml Specification</em>'.
   * @see uk.ac.kcl.inf.modelling.xdsml.henshinXDsmlSpecification.HenshinXDsmlSpecification
   * @generated
   */
  EClass getHenshinXDsmlSpecification();

  /**
   * Returns the meta object for the reference '{@link uk.ac.kcl.inf.modelling.xdsml.henshinXDsmlSpecification.HenshinXDsmlSpecification#getMetamodel <em>Metamodel</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Metamodel</em>'.
   * @see uk.ac.kcl.inf.modelling.xdsml.henshinXDsmlSpecification.HenshinXDsmlSpecification#getMetamodel()
   * @see #getHenshinXDsmlSpecification()
   * @generated
   */
  EReference getHenshinXDsmlSpecification_Metamodel();

  /**
   * Returns the meta object for the reference list '{@link uk.ac.kcl.inf.modelling.xdsml.henshinXDsmlSpecification.HenshinXDsmlSpecification#getUnits <em>Units</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference list '<em>Units</em>'.
   * @see uk.ac.kcl.inf.modelling.xdsml.henshinXDsmlSpecification.HenshinXDsmlSpecification#getUnits()
   * @see #getHenshinXDsmlSpecification()
   * @generated
   */
  EReference getHenshinXDsmlSpecification_Units();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  HenshinXDsmlSpecificationFactory getHenshinXDsmlSpecificationFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link uk.ac.kcl.inf.modelling.xdsml.henshinXDsmlSpecification.impl.HenshinXDsmlSpecificationImpl <em>Henshin XDsml Specification</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see uk.ac.kcl.inf.modelling.xdsml.henshinXDsmlSpecification.impl.HenshinXDsmlSpecificationImpl
     * @see uk.ac.kcl.inf.modelling.xdsml.henshinXDsmlSpecification.impl.HenshinXDsmlSpecificationPackageImpl#getHenshinXDsmlSpecification()
     * @generated
     */
    EClass HENSHIN_XDSML_SPECIFICATION = eINSTANCE.getHenshinXDsmlSpecification();

    /**
     * The meta object literal for the '<em><b>Metamodel</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference HENSHIN_XDSML_SPECIFICATION__METAMODEL = eINSTANCE.getHenshinXDsmlSpecification_Metamodel();

    /**
     * The meta object literal for the '<em><b>Units</b></em>' reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference HENSHIN_XDSML_SPECIFICATION__UNITS = eINSTANCE.getHenshinXDsmlSpecification_Units();

  }

} //HenshinXDsmlSpecificationPackage
