/**
 * generated by Xtext 2.12.0
 */
package uk.ac.kcl.inf.modelling.xdsml.henshinXDsmlSpecification.impl;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;

import org.eclipse.emf.ecore.impl.EFactoryImpl;

import org.eclipse.emf.ecore.plugin.EcorePlugin;

import uk.ac.kcl.inf.modelling.xdsml.henshinXDsmlSpecification.*;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model <b>Factory</b>.
 * <!-- end-user-doc -->
 * @generated
 */
public class HenshinXDsmlSpecificationFactoryImpl extends EFactoryImpl implements HenshinXDsmlSpecificationFactory
{
  /**
   * Creates the default factory implementation.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public static HenshinXDsmlSpecificationFactory init()
  {
    try
    {
      HenshinXDsmlSpecificationFactory theHenshinXDsmlSpecificationFactory = (HenshinXDsmlSpecificationFactory)EPackage.Registry.INSTANCE.getEFactory(HenshinXDsmlSpecificationPackage.eNS_URI);
      if (theHenshinXDsmlSpecificationFactory != null)
      {
        return theHenshinXDsmlSpecificationFactory;
      }
    }
    catch (Exception exception)
    {
      EcorePlugin.INSTANCE.log(exception);
    }
    return new HenshinXDsmlSpecificationFactoryImpl();
  }

  /**
   * Creates an instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public HenshinXDsmlSpecificationFactoryImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EObject create(EClass eClass)
  {
    switch (eClass.getClassifierID())
    {
      case HenshinXDsmlSpecificationPackage.HENSHIN_XDSML_SPECIFICATION: return createHenshinXDsmlSpecification();
      default:
        throw new IllegalArgumentException("The class '" + eClass.getName() + "' is not a valid classifier");
    }
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public HenshinXDsmlSpecification createHenshinXDsmlSpecification()
  {
    HenshinXDsmlSpecificationImpl henshinXDsmlSpecification = new HenshinXDsmlSpecificationImpl();
    return henshinXDsmlSpecification;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public HenshinXDsmlSpecificationPackage getHenshinXDsmlSpecificationPackage()
  {
    return (HenshinXDsmlSpecificationPackage)getEPackage();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @deprecated
   * @generated
   */
  @Deprecated
  public static HenshinXDsmlSpecificationPackage getPackage()
  {
    return HenshinXDsmlSpecificationPackage.eINSTANCE;
  }

} //HenshinXDsmlSpecificationFactoryImpl
