/*
 * generated by Xtext 2.12.0
 */
package uk.ac.kcl.inf.modelling.xdsml


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class HenshinXDsmlSpecificationRuntimeModule extends AbstractHenshinXDsmlSpecificationRuntimeModule {
}
