/*
 * generated by Xtext 2.12.0
 */
package uk.ac.kcl.inf.modelling.xdsml


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class HenshinXDsmlSpecificationStandaloneSetup extends HenshinXDsmlSpecificationStandaloneSetupGenerated {

	def static void doSetup() {
		new HenshinXDsmlSpecificationStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
