/*
 * generated by Xtext 2.12.0
 */
package uk.ac.kcl.inf.modelling.xdsml.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import uk.ac.kcl.inf.modelling.xdsml.parser.antlr.internal.InternalHenshinXDsmlSpecificationParser;
import uk.ac.kcl.inf.modelling.xdsml.services.HenshinXDsmlSpecificationGrammarAccess;

public class HenshinXDsmlSpecificationParser extends AbstractAntlrParser {

	@Inject
	private HenshinXDsmlSpecificationGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalHenshinXDsmlSpecificationParser createParser(XtextTokenStream stream) {
		return new InternalHenshinXDsmlSpecificationParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "HenshinXDsmlSpecification";
	}

	public HenshinXDsmlSpecificationGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(HenshinXDsmlSpecificationGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
