/*
 * generated by Xtext 2.12.0
 */
package uk.ac.kcl.inf.modelling.xdsml.ide.contentassist.antlr;

import com.google.inject.Inject;
import java.util.HashMap;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;
import uk.ac.kcl.inf.modelling.xdsml.ide.contentassist.antlr.internal.InternalHenshinXDsmlSpecificationParser;
import uk.ac.kcl.inf.modelling.xdsml.services.HenshinXDsmlSpecificationGrammarAccess;

public class HenshinXDsmlSpecificationParser extends AbstractContentAssistParser {

	@Inject
	private HenshinXDsmlSpecificationGrammarAccess grammarAccess;

	private Map<AbstractElement, String> nameMappings;

	@Override
	protected InternalHenshinXDsmlSpecificationParser createParser() {
		InternalHenshinXDsmlSpecificationParser result = new InternalHenshinXDsmlSpecificationParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getHenshinXDsmlSpecificationAccess().getGroup(), "rule__HenshinXDsmlSpecification__Group__0");
					put(grammarAccess.getHenshinXDsmlSpecificationAccess().getGroup_4(), "rule__HenshinXDsmlSpecification__Group_4__0");
					put(grammarAccess.getHenshinXDsmlSpecificationAccess().getMetamodelAssignment_2(), "rule__HenshinXDsmlSpecification__MetamodelAssignment_2");
					put(grammarAccess.getHenshinXDsmlSpecificationAccess().getUnitsAssignment_4_1(), "rule__HenshinXDsmlSpecification__UnitsAssignment_4_1");
				}
			};
		}
		return nameMappings.get(element);
	}
			
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public HenshinXDsmlSpecificationGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(HenshinXDsmlSpecificationGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
